Htcondor 1658 general improvements branch
ColeBollig/PATh-scripts pull request #3
Opened 2023-05-03 20:30 UTC by ColeBollig

2023-05-04 20:47 UTC, jasoncpatton requested changes
It would be nice to run this through `black` again, if it's easy for you to `pip` or `conda` install it quickly in a virtual environment. Otherwise, no worries.

2023-05-04 20:47 UTC, jasoncpatton commented on src/HTCondor/condor-9-to-10-upgrade-check.py
> +        )
I didn't even think about what `offset` would do with multiline messages, but testing shows this works right. I might suggest just omitting it for multiline messages, though, and just put whatever spaces are needed in the string itself:

```suggestion
        format_print(
            """        Failed to find 'pcre2grep' command. Will do a simple check for incompatibilties.
        Recommended to install 'pcre2grep' command for better check of map files.""",
            err=True,
        )
```

2023-05-04 20:47 UTC, jasoncpatton commented on src/HTCondor/condor-9-to-10-upgrade-check.py
>      for arg in sys.argv:
Ah, I forgot to mention that we should probably be using the `argparse` library here, but it's probably a bit too late for that. Anyway, the first arg is always the program name so can probably skip that:

```suggestion
    for arg in sys.argv[1:]:
```

2023-05-05 13:21 UTC, ColeBollig commented
@jasoncpatton I merged your suggestions and ran black on the script again

2023-05-05 13:30 UTC, jasoncpatton approved these changes

2023-05-05 13:30 UTC, jasoncpatton commented
> @jasoncpatton I merged your suggestions and ran black on the script again

LGTM!

2023-05-05 13:36 UTC, merged